name: Dependencies
on:
  pull_request:
    branches:
      - master # run the action on your projects default branch
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - run: chmod +x ./gradlew
      - run: cat > file1.txt

      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@v1
        with:
          gradle-project-path: "."
          gradle-build-module: ":app"
